#! /bin/sh
### BEGIN INIT INFO
# Provides:          carbon-cache
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Graphite Carbon backend daemon
# Description:       backend data caching and persistence daemon for Graphite
### END INIT INFO

# Author: Jonas Genannt <jonas.genannt@capi2name.de>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Graphite backend daemon"
NAME=carbon-cache
DAEMON=/usr/bin/$NAME
PIDDIR=/var/run/
DAEMON_ARGS="--config=/etc/carbon/carbon.conf --logdir=/var/log/carbon/ start"
SCRIPTNAME=/etc/init.d/$NAME
CARBON_DAEMON="cache"
INSTANCES=`grep "^\[${CARBON_DAEMON}:" /etc/carbon/carbon.conf | cut -d \[ -f 2 | cut -d \] -f 1 | cut -d : -f 2`
if [ -z "$INSTANCES" ]; then
    INSTANCES='cache'
fi

[ -x "$DAEMON" ] || exit 0

[ -r /etc/default/graphite-carbon ] && . /etc/default/graphite-carbon

. /lib/lsb/init-functions

if [ ! -r /etc/carbon/carbon.conf ]; then
	[ "$VERBOSE" != no ] && echo "Missing /etc/carbon/carbon.conf - not starting."
	exit 0
fi

if [ "$CARBON_CACHE_ENABLED" != "true" ] ; then
	[ "$VERBOSE" != no ] && echo "carbon-cache disabled in /etc/default/graphite-carbon"
	exit 0
fi

do_start()
{
    for INSTANCE in ${INSTANCES}; do
        PIDFILE=/var/run/$NAME-${INSTANCE}.pid
        ARGS=" --pidfile=${PIDFILE} --instance=${INSTANCE} ${DAEMON_ARGS}"

	    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
		    || return 1
	    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
		    $ARGS \
		    || return 2
    done
}

do_stop()
{
    STATUS=0
    for INSTANCE in ${INSTANCES}; do
        PIDFILE=/var/run/$NAME-${INSTANCE}.pid
	    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	    RETVAL="$?"
        if [ "$RETVAL" -gt 0 ]; then
            STATUS=$RETVAL
        fi
	    [ "$RETVAL" = 2 ] && continue

	    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
        if [ "$RETVAL" -gt 0 ]; then
            STATUS=$RETVAL
        fi
	    [ "$?" = 2 ] && continue

	    rm -f $PIDFILE
    done
	return "$STATUS"
}

do_status()
{
    STATUS=0
    for INSTANCE in ${INSTANCES}; do
        PIDFILE=/var/run/$NAME-${INSTANCE}.pid
	    status_of_proc -p $PIDFILE "$DAEMON" "$NAME (instance $INSTANCE)"
	    RETVAL="$?"
        if [ "$RETVAL" -gt 0 ]; then
            STATUS=$RETVAL
        fi
    done
    exit $STATUS
}

case "$1" in
	start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
	stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
	status)
        do_status
	;;
	restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;;
			*) log_end_msg 1 ;;
		esac
		;;
		*)
		log_end_msg 1
		;;
	esac
	;;
	*)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
